global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "server-1"
    static_configs:
      - targets: ["localhost:9200"]

  # BlackBox Configuration
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  
    static_configs:
      - targets:
        - https://prometheus.io/
        - https://grafana.com/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Make sure this is the correct address for your Blackbox exporter

  # Add a job for scraping the Blackbox exporter itself
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['localhost:9115']